<?php

function form_rules_form_alter(&$form, &$form_state, $form_id) {
  
  $custom_form_id = variable_get('custom_form_id', '');
  $contribution_amount_key = "civicrm_1_contribution_1_contribution_total_amount";
  $room_options_key = variable_get('room_options_key', '');
  $extra_set_key = variable_get('extra_set_key', '');
  
  $extra_room_per_night = variable_get('extra_room_per_night', '');
  $non_reach_child_acitivies = variable_get('non_reach_child_acitivies', '');
  $delegate_day_rate_member = variable_get('delegate_day_rate_member', '');
  $delegate_day_rate_non_member = variable_get('delegate_day_rate_non_member', '');
  $dinner_and_dance_tickets = variable_get('dinner_and_dance_tickets', '');
  
  $prices = array(
  	'extra_room_per_night' => variable_get('extra_room_per_night_price', ''),
  	'non_reach_child_acitivies' => variable_get('non_reach_child_acitivies_price', ''),
  	'delegate_day_rate_member' => variable_get('delegate_day_rate_member_price', ''),
  	'delegate_day_rate_non_member' => variable_get('delegate_day_rate_non_member_price', ''),
  	'dinner_and_dance_tickets' => variable_get('dinner_and_dance_tickets_price', ''),
  );
  
  $keys = array($room_options_key, $extra_room_per_night, $non_reach_child_acitivies, $delegate_day_rate_member, $delegate_day_rate_non_member, $dinner_and_dance_tickets);
  $params = array();
  $extra_total = 0;
  $room_options_total = 0;
  
  if($form_id == $custom_form_id && isset($form_state['storage'])){
	$components = $form_state['storage']['component_tree']['children'];
	$submissions = $form_state['storage']['submitted'];
	foreach ($components as $key => $value) {
		if($value['form_key'] == $extra_set_key){
			foreach ($value['children'] as $child_key => $child_value) {
				if(in_array($child_value['form_key'], $keys)){
					if(isset($submissions[$child_key])){
						$params[$child_value['form_key']] = $submissions[$child_key];
					}
				}
			}
		}else if($value['form_key'] == $room_options_key){
			$room_options_total = (int)$submissions[$key];
		}
	}

	foreach ($params as $key => $value) {
		$extra_total += ($value - 1) * $prices[$key];
	}

	$result = $extra_total + $room_options_total;
	$form['submitted'][$contribution_amount_key]['#default_value'] = (string)$result;
  }
}