<?php

function form_rules_form_alter(&$form, &$form_state, $form_id) {
  
  $awards_form_id = variable_get('awards_form_id', '');
  $brand_entries_key = variable_get('brand_entries_key', '');
  $product_number_key = variable_get('product_number_key', '');
  $submission_price_key = variable_get('submission_price_key', '');
  $contribution_amount_key = variable_get('contribution_amount_key', '');
  
  $keys = array($brand_entries_key, $product_number_key, $submission_price_key);
  $params = array();
  $resultKey = null;
  $count = 0;
  
  if($form_id == $awards_form_id && isset($form_state['storage'])){
	$components = $form_state['storage']['component_tree']['children'];
	$submissions = $form_state['storage']['submitted'];
	foreach ($components as $key => $value) {
		if(in_array($value['form_key'], $keys)){
			if(isset($submissions[$key])){
				$params[$value['form_key']] = $submissions[$key];
				$count++;
			}
		}else if($value['form_key'] == $contribution_amount_key){
			$resultKey = $key;
		}
	}

	if(!is_null($resultKey)&&$count==3){
		$result = ($params[$brand_entries_key] + $params[$product_number_key]) * $params[$submission_price_key];
		$form['submitted'][$contribution_amount_key]['#default_value'] = (string)$result;
	}
  }
}